CREATE TYPE "status" AS ENUM (
  'waiting',
  'in_auction',
  'sold'
);

CREATE TYPE "tag" AS ENUM (
  'Antique',
  'Art & Sculture',
  'Automobile',
  'Bijoux & Accessoire',
  'Collection',
  'Livre & Manuscrit',
  'Meuble',
  'Monnaie',
  'Musique',
  'Sport',
  'Vaisselle & Coutellerie',
  'Vêtement'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(32) UNIQUE NOT NULL,
  "name" varchar(32),
  "lastname" varchar(32),
  "email" varchar(128) UNIQUE NOT NULL,
  "password" varchar(132) NOT NULL,
  "profile_picture" varbinary,
  "dateofbirth" timestamp NOT NULL
);

CREATE TABLE "address" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "street" varchar(128) NOT NULL,
  "apt" int DEFAULT null,
  "city" varchar(32) NOT NULL,
  "country" VARCHAR(32) NOT NULL,
  "postal_code" CHAR(6) NOT NULL
);

CREATE TABLE "items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(32) NOT NULL,
  "description" VARCHAR(256) DEFAULT '',
  "current_status" status NOT NULL,
  "bid_count" int DEFAULT 0,
  "min_increase" numeric(5,2) DEFAULT 1,
  "id_seller" int NOT NULL,
  "auction_on" timestamp UNIQUE NOT NULL,
  "room" int
);

CREATE TABLE "bought_items" (
  "id_user" INT NOT NULL,
  "id_seller" INT NOT NULL,
  "id_item" INT UNIQUE NOT NULL,
  "bought_on" timestamp
);

CREATE TABLE "tag_list" (
  "id_item" INT,
  "id_tag" tag
);

CREATE TABLE "pictures_list" (
  "id_item" int,
  "picture" varbinary
);

CREATE TABLE "bids" (
  "id_item" int NOT NULL,
  "id_user" int NOT NULL,
  "amount" numeric(,2) NOT NULL,
  "submited_on" timestamp NOT NULL
);

COMMENT ON COLUMN "items"."room" IS 'auction_on & room must be unique';

COMMENT ON COLUMN "bids"."amount" IS 'must be higher then precious price with the same id_item';

ALTER TABLE "address" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "tag_list" ADD FOREIGN KEY ("id_item") REFERENCES "items" ("id");

ALTER TABLE "bids" ADD FOREIGN KEY ("id_item") REFERENCES "items" ("id");

ALTER TABLE "bids" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "items" ADD FOREIGN KEY ("id_seller") REFERENCES "users" ("id");

ALTER TABLE "pictures_list" ADD FOREIGN KEY ("id_item") REFERENCES "items" ("id");

ALTER TABLE "bought_items" ADD FOREIGN KEY ("id_seller") REFERENCES "users" ("id");

ALTER TABLE "bought_items" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "bought_items" ADD FOREIGN KEY ("id_item") REFERENCES "items" ("id");
